version: '3'

services:
  app:
    container_name: grupo-bamaq-app
    build:
      context: .
      dockerfile: Dockerfile
    ports:
      - "3021:8000"
    volumes:
      - .:/var/www/html
    depends_on:
      db:
        condition: service_healthy

  db:
    image: postgres:latest
    ports:
      - "5432:5432"
    environment:
      POSTGRES_DB: ${DB_DATABASE}
      POSTGRES_USER: ${DB_USERNAME}
      POSTGRES_PASSWORD: ${DB_PASSWORD}
    healthcheck:
      test: ["CMD-SHELL", "pg_isready -q -d ${DB_DATABASE} -U ${DB_USERNAME}"]
      interval: 10s
      retries: 5
      start_period: 30s
